= Cahier De Recette - DailyBankApp
:toc:
:toc-title: Sommaire

:Entreprise: DailyBank
:Equipe:  Yann Jourdan, Pauline Benghouzi, Loris Vignolles, Flavie Carlier

Créé par : Yann Jourdan, Pauline Benghouzi 

fontionnalités
 Creer un compte -> Yann JOURDAN
Cloturer un compte -> Flavie CARLIER
Debiter/crediter -> Paulinz BENGHOUZI
Virements de compte a compte -> Loris VIGNOLLES


== I. Introduction
=== 1. Objet :
[.text-justify]
Ce document a été produit dans le cadre d'un projet d'élaboration d'une application bancaire pour ...


== II. Pre-Requis :
[.text-justify]
L'exécution des tests spécifiés au chapitre suivant requiert :

* Une base de données installée (référence document technique).
* L'environnement de test tel que spécifié dans la partie "Environnement de test" de ce document.
* Les fiches de tests. *À vérifier*


=== 1. Éléments à tester :
[.text-justify]
Les éléments testés concernent les Use-Cases spécifiés dans la *documentation technique*.


=== 2. Environnement de test :
[.text-justify]
Ordinateur sous Windows ou OS équivalent.



== III. Cas de test :
=== 1. Fonctionnalités des guichetiers :
==== 1.1 Gestion des clients :

|====

>|Cas de test 4+|Test-01-01-01
>|Titre 4+|Création d'un nouveau client
>|Objectif 4+| Vérifier qu'il est possible de créer un nouveau client

5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_C.1 ^|Cliquer sur le bouton "Nouveau client". ^|La fenêtre de création des clients s'ouvre. ^| aucune ^|OK
^|All_G_C.2 ^|Compléter les champs spécifiés et valider. ^|Un nouveau client est créé. ^|aucune ^|OK

|====

>|Cas de test 4+|Test-01-01-02
>|Titre 4+|Generer un relevé mensuel en pdf 
>|Objectif 4+| Vérifier qu'il est possible de generer un relevé mensuel en pdf 
5+|
^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_C.1 ^|Cliquer sur le bouton "Generer relevé pdf ". ^|La fenêtre des relevés s'ouvre. ^| un client actif est séléctionné ^|OK
^|All_G_C.2 ^|Compléter les champs spécifiés et valider. ^|un pdf est généré. ^|aucune ^|OK


5+|Commentaire :
Compléter et si on ne valide pas, ...
|====


>|Cas de test 4+|Test-01-01-02
>|Titre 4+|Modification d'un client
>|Objectif 4+| Vérifier qu'il est possible de modifier un client

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_C.3 ^|Cliquer sur le bouton "Modifier client". ^|La fenêtre de modification des données du clients s'ouvre. ^|Le client est sélectionné ^|OK
^|All_G_C.4 ^|Modifier les champs souhaités et confirmer. ^|Retour sur les informations du client. Le client est modifié. ^|La fenêtre modifier client est active ^|OK
^|All_G_C.5 ^|Modifier les champs souhaités et annuler. ^|Retour sur les informations du client. Le client est inchangé. ^|La fenêtre modifier client est active ^|OK

|====


==== 1.2 Gestion des comptes bancaires :




|====
>|Cas de test 4+|Test-01-02-05
>|Titre 4+|Cloturer un compte
>|Objectif 4+| Vérifier qu'il est possible de cloturer un compte

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_CB.1 ^|Cliquer sur le bouton "Cloturer Compte". ^|Le compte apparait comme cloturé. ^| un compte actif soit séléctionné ^|OK
...

|====

|====
>|Cas de test 4+|Test-01-02-04
>|Titre 4+|Création un nouveau compte
>|Objectif 4+| Vérifier qu'il est possible de crée un nouveau compte 

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_CB.1 ^|Cliquer sur le bouton "Nouveau Compte". ^|La page de création de compte s’affiche. ^| aucune ^|OK
^|All_G_CB.2 ^|Entrer des information pour al creation du compte. ^|Les informations sont rentée dans le nouveau compte. ^|aucune ^|OK
...

|====


|====

>|Cas de test 4+|Test-01-02-03
>|Titre 4+|Consultation d'un compte
>|Objectif 4+| Vérifier qu'il est possible de consulter un compte

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_CB.1 ^|Cliquer sur le bouton "Comptes client". ^|La page des comptes du client s’affiche. ^|Un client actif est sélectionné ^|OK
^|All_G_CB.2 ^|Sélectionner le bouton "Voir opérations". ^|La page des opérations du compte s’affiche. ^|Un compte actif est sélectionné ^|OK
...

|====




==== 1.3 Gestion des opérations :
|====
>|Cas de test 4+|Test-01-03-04
>|Titre 4+| Gerer les prélevement automatiques  - CRUD
>|Objectif 4+| Vérifier qu'il est possible de gerer les prélevements automatiques

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_CB.1 ^|Cliquer sur le bouton "gerer les prélevement auto". ^|La page de gestion des prélevement s'ouvre. ^|aucun ^|OK
^|All_G_CB.2 ^|modifier les valeur de prelevement. ^|Les nouvelles valeur de prelevement sont affiché ^|aucun ^|OK


|====
>|Cas de test 4+|Test-01-03-03
>|Titre 4+| Effectuer un virement
>|Objectif 4+| Vérifier qu'il est possible d'effectuer un virement

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_CB.1 ^|Cliquer sur le bouton "effectuer un virement". ^|La page des virements s’affiche. ^|un compte a debiter et un compte à crediter est selectionné ^|OK
^|All_G_CB.2 ^|Rentrer un montant 50 dans le champ "Montant". ^|Le nouveau solde du compte debiteur est 150euros, celui du compte créditeur est de 50€. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date ^|pas de precondition particulière Les compte sélectionnés ont un solde de +100 euros
 ^|OK
 
|====



|====
>|Cas de test 4+|Test-01-03-02
>|Titre 4+|Crediter un compte
>|Objectif 4+| Vérifier qu'il est possible de debiter et ou crediter un compte

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_CB.1 ^|Cliquer sur le bouton "Crediter un compte". ^|La page des credits s’affiche. ^|un compte a crediter est selectionné ^|OK
^|All_G_CB.2 ^|Rentrer un montant 50 dans le champ "Montant". ^|Le nouveau solde est 150euros. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date ^|pas de precondition particulière Le compte sélectionné a un solde de +100 euros
 ^|OK
 
|====
|====

>|Cas de test 4+|Test-01-03-01
>|Titre 4+|Débiter un compte
>|Objectif 4+| Vérifier qu'il est possible de débiter un compte

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|All_G_COP.1 ^|Cliquer sur le bouton "Enregistrer Débit". ^|La page des débit du compte s’affiche. ^| Un compte actif est sélectionné ^|OK
^|All_G_COP.2  ^|Rentrer un montant 50 dans le champ "Montant". ^|Le nouveau solde est +50euros. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date ^| Le compte sélectionné a un solde de +100 euros
 ^|OK
^|All_G_COP.3  ^|Rentrer un montant 150 dans le champ "Montant". ^|Le nouveau solde est -50 euros. On a créé une nouvelle opération dans la liste des opérations avec le bon montant et la bonne date ^| Le compte sélectionné a un solde de +100 euros, le découvert
autorisé est de -100 euros.
 ^|OK
^|All_G_COP.4  ^|Rentrer un montant 250 dans le champ "Montant". ^|Blocage ! + pop-up ^| Le compte sélectionné a un solde de +100 euros, le découvert
autorisé est de -100 euros.
 ^|OK
  
 

|====






=== 2. Fonctionnalités des chefs d'agence :
[.text-justify]
Les chefs d'agence ont accès aux mêmes fonctionnalités que les guichetiers, ainsi que d'autres qui leur sont réservées.

==== 2.1 Gestion des clients :
|====
>|Cas de test 4+|Test-02-01-04
>|Titre 4+|Simuler une assurance d'emprunt 
>|Objectif 4+| Vérifier qu'il est possible de simuler une assurance d'emprun

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_C.1 ^|Cliquer sur le bouton "Simuler une assurance d'emprun". ^|La page des assurances s’affiche. ^|un compte simuler est selectionné ^|OK
^|C_G_C.2 ^|Simuler une assurance d'emprunt d'un compte selectionné  ^|La fennetre montre les informations de l'emprunt et de l'assurance sans les enregistrer dans le compte  ^| aucune ^| OK
|====


|====
>|Cas de test 4+|Test-02-01-03
>|Titre 4+|Simuler un emprunt 
>|Objectif 4+| Vérifier qu'il est possible de simuler un emprunt 

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_C.1 ^|Cliquer sur le bouton "Simuler un emprunt". ^|La page des emprunt s’affiche. ^|un compte simuler est selectionné ^|OK
^|C_G_C.2 ^|Simuler un emprunt d'un compte selectionné  ^|La fennetre montre les informations de l'emprunt sans les enregistrer dans le compte  ^| aucune ^| OK
|====



|====

>|Cas de test 4+|Test-02-01-02
>|Titre 4+|Effectuer un debit exceptionnel 
>|Objectif 4+| Vérifier qu'il est possible d'effectuer un debit exceptionnel 

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_C.1 ^|Debiter un compte dont le decouvert d'autorise pas de debit ^|Le compte est débité  ^| aucune ^| OK

|====

|====

>|Cas de test 4+|Test-02-01-01
>|Titre 4+|Rendre inactif un client
>|Objectif 4+| Vérifier qu'il est possible de rendre un client inactif

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_C.1 ^|Sélectionner le bouton "Inactif" et confirmer. ^|...  ^|Un client actif est sélectionné ^| OK

5+|

5+|Commentaire : REVOIR AVEC
 *clôturés*.|

|====
==== 2.2 Gestion des employés :
|====
>|Cas de test 4+|Test-02-02-01
>|Titre 4+|Gerer les employes - CRUD
>|Objectif 4+| Vérifier qu'il est possible de Gerer les employes

5+|

^|ID ^|Action ^|Comportement attendu ^|Pré-conditions ^|Résultat
^|C_G_C.1 ^|Cliquer sur le bouton "Gerer les employes". ^|La page du CRUD s’affiche. ^|aucune ^|OK
^|C_G_C.2 ^|Utiliser le CRUD create. ^|un nouvel employés est ajouté a la liste. ^|aucune ^|OK
^|C_G_C.3 ^|Utiliser le CRUD read. ^|une fennetre avec les informations de l'employé selectionné s'affiche. ^|un employé doit etre séléctionné ^|OK
^|C_G_C.4 ^|Utiliser le CRUD update. ^|une fennetre avec les informations de l'employé selectionné s'affiche avec la possibilité de les modifier  ^|un employé doit etre séléctionné ^|OK
^|C_G_C.5 ^|Utiliser le CRUD delete  ^|l'employé selectionné est effacé ^|un employé doit etre séléctionné  ^|OK
|====
